// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/WorkbenchLedgerCamera/WorkbenchLedgerCamera.tsx": () => import("../components/mockups/WorkbenchLedgerCamera/WorkbenchLedgerCamera.tsx"),
  "./components/mockups/WorkbenchLedgerDispatch/WorkbenchLedgerDispatch.tsx": () => import("../components/mockups/WorkbenchLedgerDispatch/WorkbenchLedgerDispatch.tsx"),
  "./components/mockups/WorkbenchLedgerEvening/WorkbenchLedgerEvening.tsx": () => import("../components/mockups/WorkbenchLedgerEvening/WorkbenchLedgerEvening.tsx"),
  "./components/mockups/WorkbenchLedgerFlow/WorkbenchLedgerFlow.tsx": () => import("../components/mockups/WorkbenchLedgerFlow/WorkbenchLedgerFlow.tsx"),
  "./components/mockups/WorkbenchLedgerHome/WorkbenchLedgerHome.tsx": () => import("../components/mockups/WorkbenchLedgerHome/WorkbenchLedgerHome.tsx"),
  "./components/mockups/templates/CottagecoreFintechHomeScreen-HWBZ5K/App.tsx": () => import("../components/mockups/templates/CottagecoreFintechHomeScreen-HWBZ5K/App.tsx"),
  "./components/mockups/templates/SwissWineryAdminDashboard-N6UxQ6/App.tsx": () => import("../components/mockups/templates/SwissWineryAdminDashboard-N6UxQ6/App.tsx"),
  "./components/mockups/templates/swiss-people-register-variant/SwissWineryPeopleRegisterVariant.tsx": () => import("../components/mockups/templates/swiss-people-register-variant/SwissWineryPeopleRegisterVariant.tsx")
};
